language: python
notifications:
  irc:
    channels:
      - "irc.esper.net#L"
    on_success: always
    on_failure: always
    skip_join: true
python:
  - "2.6"
  - "2.7"
# command to run tests
before_script: chmod +x debug
script: ./debug
