language: python
python:
  - "2.6"
  - "2.7"
# command to run tests
script: ./debug
notifications:
  irc:
    channels:
      - "irc.esper.net#L"
    template:
      - "Building Code... (ID) %{build_number} on (Branch) %{branch} by %{author}"
      - "%{repository} (%{commit}) : %{message}"
      - "Build details: %{build_url}"
