language: python
python:
  - "2.6"
  - "2.7"
install: "pip install pep8"
# command to run tests
script: cd util; bash debug
notifications:
  irc:
    channels:
      - "irc.esper.net#L"
    template:
      - "%{repository_slug} (%{build_id}): %{message} %{result} - %{build_url} "
