language: php
notifications:
  irc:
    channels:
      - "irc.esper.net#L"
    on_success: always
    on_failure: always
    skip_join: true
# command to run tests
before_script: chmod +x debug
script: ./debug
