language: python
python:
  - "2.6"
  - "2.7"
# command to run tests
script: ./debug
notifications:
  irc:
    channels:
      - "irc.esper.net#L"
    #  - "chat.freenode.net#some-other-channel"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: false
